services:
  postgres:
    image: postgres:16-alpine
    container_name: immo_postgres
    environment:
      POSTGRES_DB: immo_prestige
      POSTGRES_USER: immo
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - immo_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U immo -d immo_prestige"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: immo_redis
    ports:
      - "6379:6379"
    volumes:
      - immo_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  immo_pgdata:
  immo_redisdata:
